
@tag
Feature: Tree
Iwanttousethistemplateformyfeaturefile
Background: TheusersignindsAlgoPortal
@tag1
Scenario: VerifythatuserisabletonavigatetoTreeDataStruturepage
Given TheuserisintheHomePageafterSignin
When the_user_clicks_the_getting_started_button_in_tree_ds
When TheuserselectTreeItemfromDropdownmenu
Then TheuserbedirectedtoTreedatastructurepage

Scenario: VerifythatuserisabletooverviewofTreeinTreepage
Given TheuserisinTreePageaftersignin
When Theuserclickoverviewoftreeintreelink
Then TheuserbedirectedtooperationinTreePage
Scenario: VerifythatuserisabletonavigatetotryEditorPageforoverviewofTreeinTreePage
Given TheuserinontheoverviewofTreeinTreePage
When TheuserclicksTryHerebuttoninoverviewofTreeinTreepage
Then TheuserShouldberedirectedtopagehavingantryEditorwithaRunbuttontotest
Scenario: VerifythatuserreceiveerrorwhenclickonrunbuttonwithoutenteringcodeforoverviewofTreeinTreePage
Given TheuserisintryEditorpage.
When Theuserclickstherunbuttonwithoutenteringthecodeintheeditor
Then Theusershouldnotseeanyerrormessageoroutput.
Scenario: VerifythatuserreceiveerrorforinvalidphythoncodeforOverviewofTreeinTreePage
Given TheuserisintryEditorpage.
When Theuserwritetheinvalidcodeandclickstherunbuttonintheeditor
Then Theusershouldabletoseeerrormessageinalertwindow.

   
 